CREATE TABLE [dbo].[Agency]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[CreatedAt] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[UpdatedAt] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[Number] VARCHAR(4) NOT NULL,
	[Digit] TINYINT NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
	CONSTRAINT UQ_Agency_Number UNIQUE ([Number])
)

GO
