CREATE TABLE [dbo].[Client]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[CreatedAt] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[UpdatedAt] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[Name] NVARCHAR(100) NOT NULL, 
	[Cpf] VARCHAR(14) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
	CONSTRAINT UQ_Client_Cpf UNIQUE ([Cpf]),
)

GO
